// BANK_ENJA: English fortune sentences + Japanese paired translation.
// Structure matches 100% horoscope bank.js style: category -> {a,b,c} -> array.
// Note: Keep texts natural, avoid repeated stock phrases, and keep TOEIC-friendly vocabulary.

const BANK_ENJA = {
  overall: {
    a: [
      { en: "Your timing is excellent today. If you act decisively, you can turn a small chance into a clear win.", ja: "今日はタイミングが良い日です。迷わず動けば、小さなチャンスを確かな成果に変えられます。" },
      { en: "A clean decision will unlock momentum. Choose one priority and execute it without hesitation.", ja: "決断を一つクリアにすると勢いが出ます。優先順位を一つ選び、迷わず実行しましょう。" },
      { en: "Your focus is sharp. Handle the most important item first, and everything else will follow smoothly.", ja: "集中力が冴えています。最重要項目を先に片付けると、他もスムーズに流れます。" },
      { en: "You can communicate with unusual clarity. A brief message or statement will have strong impact.", ja: "普段以上に明快に伝えられます。短い一言でも、十分に影響力があります。" },
      { en: "A practical plan works perfectly. Put it in writing and move step by step—results will be visible.", ja: "現実的な計画がうまく機能します。書き出して一歩ずつ進めると、成果が見えてきます。" },
      { en: "You are supported by a steady rhythm. Maintain your pace and finish what you started.", ja: "安定した流れに支えられています。ペースを保ち、着手したことを最後までやり切りましょう。" },
      { en: "Your judgment is reliable. If you choose the simplest option, it will outperform the complicated one.", ja: "判断が安定しています。複雑な案より、シンプルな案のほうが結果を出します。" },
      { en: "An opportunity appears in the middle of routine work. Notice it, and take initiative.", ja: "日常の作業の中に好機が潜んでいます。見逃さず、主体的に動いてみましょう。" },
      { en: "You can raise quality without extra effort. Tighten the basics—accuracy and speed will improve together.", ja: "余計な負荷を増やさずに質を上げられます。基本を締めると、精度とスピードが同時に上がります。" },
      { en: "Today rewards consistency. A small, repeated action will create a surprisingly strong outcome.", ja: "今日は継続が報われます。小さな行動の積み重ねが、想像以上に強い結果を生みます。" },
      { en: "You can recover lost time. Reduce distractions for one hour and complete a task you have avoided.", ja: "遅れを取り戻せます。1時間だけ雑音を減らし、先延ばししていた作業を完了させましょう。" },
      { en: "Your energy is balanced. If you protect your schedule, you will end the day feeling satisfied.", ja: "エネルギー配分が良好です。予定を守れば、納得感のある一日になります。" },
    ],
    b: [
      { en: "Progress is steady. If you organize your priorities, you will avoid unnecessary stress.", ja: "進み方は安定しています。優先順位を整理すれば、無駄なストレスを避けられます。" },
      { en: "Nothing is urgent, but details matter. Review your plan once and adjust gently.", ja: "緊急事態ではありませんが、細部が大事です。計画を一度見直し、軽く調整しましょう。" },
      { en: "Your pace is fine. Do not rush—consistent work will be more efficient than quick fixes.", ja: "ペースは十分です。焦らず、場当たりよりも着実な作業のほうが効率的です。" },
      { en: "Choose a realistic target. Completing one task fully is better than touching five tasks halfway.", ja: "現実的な目標を選びましょう。5つを半端に触るより、1つを完了させるほうが価値があります。" },
      { en: "Communication improves if you simplify. Use short sentences and confirm the key point.", ja: "伝達はシンプルにすると改善します。短文で、要点を確認しましょう。" },
      { en: "A calm approach works best. Protect your time and keep a small buffer in your schedule.", ja: "落ち着いた進め方が最適です。時間を守り、予定に少し余白を作りましょう。" },
      { en: "If you feel scattered, return to the basics. A checklist will restore control quickly.", ja: "散らばる感覚があれば基本へ戻りましょう。チェックリストで素早く立て直せます。" },
      { en: "Today favors maintenance. Improve one weak point and keep everything else stable.", ja: "今日は維持・整備向きです。弱点を一つだけ改善し、他は安定させましょう。" },
      { en: "You can gain trust through small actions. Respond on time and keep your promise.", ja: "小さな行動で信頼を積めます。返信を遅らせず、約束を守りましょう。" },
      { en: "Avoid extremes. A moderate decision will be safer and still effective.", ja: "極端は避けましょう。中庸な判断が安全で、十分に効果も出ます。" },
      { en: "If you hesitate, write it down. Seeing options on paper will clarify the next step.", ja: "迷ったら書き出しましょう。紙に出すだけで次の一手が明確になります。" },
      { en: "A small change in routine helps. Adjust one habit and measure the result.", ja: "ルーティンの小さな変更が効きます。習慣を一つ調整して、結果を確認しましょう。" },
    ],
    c: [
      { en: "Keep your plan simple today. Too many options will reduce accuracy and slow you down.", ja: "今日は計画をシンプルに。選択肢を増やしすぎると精度が落ち、スピードも下がります。" },
      { en: "Noise around you may increase. Protect your focus by limiting information and notifications.", ja: "周囲のノイズが増えそうです。情報や通知を絞って集中を守りましょう。" },
      { en: "Double-check before you commit. A small oversight can create a larger correction later.", ja: "確定する前に二重チェックを。小さな見落としが、後で大きな修正になります。" },
      { en: "Do not force a quick conclusion. If possible, postpone major decisions until tomorrow.", ja: "急いで結論を出さないでください。可能なら大きな決断は明日に回しましょう。" },
      { en: "Energy may drop unexpectedly. Reduce your workload and aim for a clean minimum.", ja: "エネルギーが急に落ちやすい日です。負荷を減らし、最小限をきれいにこなしましょう。" },
      { en: "Miscommunication is likely if you assume. Confirm facts and repeat the key details.", ja: "思い込みで進めると誤解が起きやすいです。事実を確認し、要点を復唱しましょう。" },
      { en: "Avoid unnecessary conflict. Choose neutral language and keep boundaries clear.", ja: "不要な衝突は避けましょう。中立的な言い方にして、境界線をはっきりさせてください。" },
      { en: "If something feels off, pause. A short reset will prevent a bigger mistake.", ja: "違和感があれば一度止まりましょう。短いリセットが大きなミスを防ぎます。" },
      { en: "Today is not for risky bets. Prefer reliability over excitement.", ja: "今日はリスクを取る日ではありません。刺激よりも確実さを選びましょう。" },
      { en: "Do one thing at a time. Multitasking will increase errors and reduce quality.", ja: "同時並行は避けて一つずつ。マルチタスクはエラーが増え、品質が下がります。" },
      { en: "Your schedule may get disrupted. Keep a buffer and prepare a backup plan.", ja: "予定が崩れやすい日です。余白を取り、代替案を用意しましょう。" },
      { en: "Treat today as maintenance. Clean up,整理, and prepare for the next move.", ja: "今日は整備日にしましょう。片付け・整理をして、次の一手に備えてください。" },
    ],
  },

  love: {
    a: [
      { en: "Your message lands beautifully today. Speak honestly and keep it simple.", ja: "今日は言葉が綺麗に届きます。正直に、そしてシンプルに伝えてみてください。" },
      { en: "A warm gesture will be remembered. Choose a small action that shows respect.", ja: "温かい行動が記憶に残ります。敬意が伝わる小さな行動を選びましょう。" },
      { en: "If you want to reconnect, today is ideal. Send one clear message and wait calmly.", ja: "距離を縮めたいなら今日は最適です。明確な一通を送り、落ち着いて待ちましょう。" },
      { en: "You can set a boundary without tension. A calm tone will protect both sides.", ja: "今日は緊張を生まずに境界線を示せます。落ち着いたトーンが双方を守ります。" },
      { en: "Trust grows through consistency. Keep your promise, even in small things.", ja: "信頼は一貫性で育ちます。小さなことでも約束を守りましょう。" },
      { en: "A sincere compliment works. Be specific about what you appreciate.", ja: "誠実な褒め言葉が効きます。何が良いのかを具体的に伝えてください。" },
      { en: "Timing favors conversation. Ask one thoughtful question and listen fully.", ja: "会話のタイミングが良い日です。思慮ある質問を一つして、最後まで聞きましょう。" },
      { en: "You can resolve a misunderstanding quickly. Clarify one detail and move on.", ja: "誤解は素早く解けます。1点だけ明確にして前へ進みましょう。" },
      { en: "Your presence feels reassuring. Stay steady, and the relationship becomes more stable.", ja: "あなたの存在が安心感になります。安定した態度が関係をより安定させます。" },
      { en: "A gentle initiative is rewarded. Suggest a plan that is easy to accept.", ja: "やさしい提案が報われます。相手が受け入れやすい計画を提示してみてください。" },
      { en: "If you are single, a natural connection may appear. Show up as yourself.", ja: "シングルなら自然な縁が現れそうです。背伸びせず、そのままの自分で。" },
      { en: "Today supports forgiveness. Release a small grudge and you will feel lighter.", ja: "今日は許しに追い風があります。小さなしこりを手放すと心が軽くなります。" },
    ],
    b: [
      { en: "Keep the tone gentle. A calm reply will prevent unnecessary tension.", ja: "トーンは穏やかに。落ち着いた返信が余計な緊張を防ぎます。" },
      { en: "Avoid guessing. If you are unsure, ask directly and confirm.", ja: "推測は避けましょう。曖昧なら直接聞いて確認を。" },
      { en: "Small care matters today. A simple check-in message is enough.", ja: "今日は小さな気遣いが効きます。軽い一言の連絡で十分です。" },
      { en: "Do not push for a conclusion. Let the conversation breathe.", ja: "結論を急がないでください。会話に余白を作りましょう。" },
      { en: "If emotions rise, slow down. Choose one point and speak clearly.", ja: "感情が上がったらスピードを落として。要点を一つに絞って明確に話しましょう。" },
      { en: "A misunderstanding may come from timing. Reply when you can focus.", ja: "誤解はタイミングから起きやすいです。集中できる時に返信しましょう。" },
      { en: "Respect your boundaries. Saying " + "" + "no" + "" + " politely is better than resenting later.", ja: "境界線を尊重してください。後で不満を溜めるより、丁寧に『NO』と言うほうが良いです。" },
      { en: "Today is good for maintenance. Keep things stable rather than dramatic.", ja: "今日は維持向きです。ドラマよりも安定を選びましょう。" },
      { en: "Listen more than you talk. Understanding improves with patience.", ja: "話すより聞くを多めに。忍耐が理解を深めます。" },
      { en: "Choose kindness, not perfection. A small mistake is not a big deal.", ja: "完璧より親切を。小さなミスは大問題ではありません。" },
      { en: "If you feel distant, return to basics: greet, confirm, and appreciate.", ja: "距離を感じたら基本へ：挨拶・確認・感謝。" },
      { en: "Keep your expectations realistic. This will protect your mood.", ja: "期待値は現実的に。それが気分を守ります。" },
    ],
    c: [
      { en: "Avoid sharp words today. Even a small comment can be taken too seriously.", ja: "今日は強い言葉を避けましょう。小さな一言でも重く受け取られがちです。" },
      { en: "Do not over-interpret silence. If you need clarity, ask once and stop.", ja: "沈黙を深読みしないでください。必要なら一度だけ聞き、そこで止めましょう。" },
      { en: "Emotions can swing. If you feel irritated, take space before replying.", ja: "感情が揺れやすい日です。イラっとしたら返信前に距離を取りましょう。" },
      { en: "Today is not ideal for ultimatums. Protect the relationship by lowering intensity.", ja: "今日は最後通牒は不向きです。強度を下げることが関係を守ります。" },
      { en: "Misunderstandings are likely. Confirm details and avoid assumptions.", ja: "誤解が起きやすいです。詳細を確認し、思い込みを避けてください。" },
      { en: "If a topic feels heavy, postpone it. Choose a lighter conversation.", ja: "話題が重いと感じたら延期を。軽い会話を選びましょう。" },
      { en: "Boundaries matter more than sympathy today. Keep your limits clear.", ja: "今日は共感より境界線が重要です。限界ラインを明確に。" },
      { en: "Avoid comparing. Focus on what is working, not what is missing.", ja: "比較は避けましょう。足りないものより、うまくいっている点に注目を。" },
      { en: "Do not chase certainty. Let things settle naturally.", ja: "確実さを追いすぎないで。自然に落ち着くのを待ちましょう。" },
      { en: "A short apology can prevent a long conflict. Keep it simple.", ja: "短い謝罪が長い衝突を防ぎます。シンプルに。" },
      { en: "If you feel drained, protect your energy. Say no to extra demands.", ja: "疲れを感じるならエネルギーを守って。追加の要求は断りましょう。" },
      { en: "Choose stability over excitement today. Quiet care is enough.", ja: "今日は刺激より安定を。静かな気遣いで十分です。" },
    ],
  },

  work: {
    a: [
      { en: "Your output can exceed expectations. Focus on quality, then deliver on time.", ja: "期待を上回る成果が出せます。品質に集中し、期限内に出しましょう。" },
      { en: "A negotiation goes in your favor if you prepare. Confirm your conditions and speak clearly.", ja: "準備すれば交渉は有利に進みます。条件を確認し、明確に話しましょう。" },
      { en: "You can solve a tricky problem quickly. Break it into steps and finish the first one now.", ja: "難しい問題も早く解けます。手順に分け、まず一歩目を今やりましょう。" },
      { en: "Today supports leadership. Take initiative and set the pace for others.", ja: "今日は主導権が取れます。率先して動き、周囲のペースを作りましょう。" },
      { en: "Your schedule aligns well. Use the window of focus to complete a high-impact task.", ja: "予定の噛み合わせが良い日です。集中できる時間帯に影響の大きい作業を完了させて。" },
      { en: "A clear document wins. Write a short summary and align the team.", ja: "短いドキュメントが効きます。要点をまとめ、チームの認識を揃えましょう。" },
      { en: "Feedback is constructive today. Ask for it, then refine your work immediately.", ja: "今日はフィードバックが建設的です。もらってすぐに修正へ反映しましょう。" },
      { en: "You can improve efficiency by simplifying. Remove one unnecessary step from your workflow.", ja: "シンプル化で効率が上がります。作業手順から不要な一手を削りましょう。" },
      { en: "Your decisions are trusted. Choose the practical option and commit.", ja: "判断が信頼されます。現実的な案を選び、腹を決めましょう。" },
      { en: "A meeting can become productive. Set an agenda and keep it short.", ja: "会議が有益になりやすい日です。議題を立て、短く終えましょう。" },
      { en: "Deadlines feel manageable. Prioritize, execute, and report progress.", ja: "締切は管理可能です。優先順位を付けて実行し、進捗を共有しましょう。" },
      { en: "Your concentration is strong. Protect it by turning off distractions.", ja: "集中力が強い日です。通知などを切って守りましょう。" },
    ],
    b: [
      { en: "Work moves forward steadily. Confirm the next step and keep your pace.", ja: "仕事は着実に進みます。次の一手を確認し、ペースを保ちましょう。" },
      { en: "Details matter more than speed. Review once before submitting.", ja: "スピードより細部が重要です。提出前に一度見直しましょう。" },
      { en: "Avoid multitasking. Completing one task will raise overall efficiency.", ja: "マルチタスクは避けましょう。1つ完了させると全体効率が上がります。" },
      { en: "If collaboration is slow, clarify responsibilities. One clear owner improves flow.", ja: "連携が遅いなら責任範囲を明確に。担当を1人決めると流れが良くなります。" },
      { en: "A calm message prevents confusion. Write short, confirm, and proceed.", ja: "落ち着いた連絡が混乱を防ぎます。短く書いて確認し、進めましょう。" },
      { en: "Today is good for maintenance tasks. Clean up files, notes, and open threads.", ja: "今日は整備作業に向きます。ファイル・メモ・未完了のやり取りを整理しましょう。" },
      { en: "If you feel stuck, ask one question. A small hint can unlock progress.", ja: "詰まったら質問を一つ。小さなヒントで前に進めます。" },
      { en: "Keep your standard consistent. Do not over-polish; finish and ship.", ja: "基準は一定に。磨きすぎず、終わらせて出しましょう。" },
      { en: "Measure the result. A quick check will prevent rework later.", ja: "結果を測りましょう。早い確認が後の手戻りを防ぎます。" },
      { en: "Stay flexible. A minor change in plan can improve the outcome.", ja: "柔軟に。小さな計画変更が結果を良くします。" },
      { en: "Choose clarity over volume. Fewer messages with clear meaning work best.", ja: "量より明確さを。少ない連絡でも意味がはっきりしているほうが良いです。" },
      { en: "Protect a focus block. One uninterrupted hour will be valuable.", ja: "集中時間を確保しましょう。中断のない1時間が価値になります。" },
    ],
    c: [
      { en: "Avoid rushing today. A small mistake can cost more time than you save.", ja: "今日は急がないで。小さなミスが節約以上の時間を奪います。" },
      { en: "Miscommunication is likely. Confirm requirements and repeat key details.", ja: "誤解が起きやすいです。要件を確認し、要点を繰り返しましょう。" },
      { en: "Do not take on extra tasks. Protect your capacity and finish the essentials.", ja: "追加の仕事を背負わないでください。キャパを守り、必須を終わらせましょう。" },
      { en: "If the timeline is tight, simplify the scope. Reduce features, keep quality.", ja: "スケジュールが厳しいならスコープを絞りましょう。機能を減らし、品質を守って。" },
      { en: "Today is not ideal for confrontation. Use neutral language and document decisions.", ja: "今日は対立は不向きです。中立的に話し、決定事項は記録しましょう。" },
      { en: "Expect interruptions. Build a buffer and protect the most important block.", ja: "割り込みが入りやすいです。余白を作り、最重要の時間帯を守りましょう。" },
      { en: "If you feel overloaded, reset. Close one loop, then stop.", ja: "過負荷ならリセットを。未完了を1つ閉じて、そこで止めましょう。" },
      { en: "Avoid optimistic estimates. Use conservative numbers and confirm resources.", ja: "楽観的な見積もりは避けて。保守的な数値で、リソースも確認しましょう。" },
      { en: "A delay may be safer than a flawed delivery. Prioritize reliability.", ja: "不完全な納品より延期のほうが安全です。確実さを優先しましょう。" },
      { en: "Keep records today. Notes will prevent confusion later.", ja: "今日は記録を残して。メモが後の混乱を防ぎます。" },
      { en: "If you must decide, choose the simplest option. Complexity increases risk.", ja: "決める必要があるなら最もシンプルな案を。複雑さはリスクを増やします。" },
      { en: "Protect your attention. Turn off notifications and work in short bursts.", ja: "注意力を守って。通知を切り、短い集中で進めましょう。" },
    ],
  },

  money: {
    a: [
      { en: "A smart choice saves money today. Review subscriptions and keep only what you use.", ja: "今日は賢い選択で節約できます。サブスクを見直し、使うものだけ残しましょう。" },
      { en: "You can negotiate or ask for a better deal. If you check conditions, you may win.", ja: "条件を確認すれば、交渉や割引が通りやすい日です。" },
      { en: "Your judgment is practical. Buy for value, not impulse, and you will feel satisfied.", ja: "判断が現実的です。衝動ではなく価値で買うと、納得できます。" },
      { en: "A small investment in quality pays off. Choose durable options.", ja: "品質への小さな投資が報われます。長く使えるものを選びましょう。" },
      { en: "Today supports budgeting. Set a clear limit and you will keep control easily.", ja: "今日は予算管理がうまくいきます。上限を決めると、簡単にコントロールできます。" },
      { en: "You can find a simple saving strategy. Automate one part and reduce friction.", ja: "シンプルな節約策が見つかります。1つ自動化して摩擦を減らしましょう。" },
      { en: "Unexpected support may arrive. Accept it with gratitude and keep records.", ja: "思わぬ援助が入りそうです。感謝して受け取り、記録も残しましょう。" },
      { en: "A clear plan prevents waste. Make a list before you purchase.", ja: "明確な計画が無駄を防ぎます。購入前にリストを作りましょう。" },
      { en: "Today is good for reviewing contracts. One check can prevent a future loss.", ja: "契約の見直しに良い日です。1回の確認が将来の損を防ぎます。" },
      { en: "You can increase efficiency: buy less, but buy better.", ja: "効率を上げられます。少なく買って、より良いものを選びましょう。" },
      { en: "If you sell something, timing is favorable. Present it clearly and respond quickly.", ja: "売るならタイミングが良いです。分かりやすく提示し、素早く対応しましょう。" },
      { en: "A calm decision improves your financial outcome. Avoid rush and choose wisely.", ja: "落ち着いた判断が金運を上げます。焦らず賢く選びましょう。" },
    ],
    b: [
      { en: "Keep spending moderate. A small adjustment is enough to stay on track.", ja: "支出は控えめに。小さな調整で軌道に乗ります。" },
      { en: "Avoid impulsive purchases. Wait 10 minutes and confirm if you still need it.", ja: "衝動買いは避けましょう。10分待って、本当に必要か確認を。" },
      { en: "Review your budget once. You will notice one easy place to reduce costs.", ja: "予算を一度見直すと、簡単に削れる箇所が1つ見つかります。" },
      { en: "Today is good for maintenance, not expansion. Keep things stable.", ja: "今日は拡大より維持の日です。安定を選びましょう。" },
      { en: "If you lend money, set conditions clearly. Clarity prevents stress.", ja: "お金を貸すなら条件を明確に。明確さがストレスを防ぎます。" },
      { en: "Choose value over appearance. Function will save you money long-term.", ja: "見た目より価値を。機能性は長期的に節約になります。" },
      { en: "A routine check helps. Track expenses for one day and adjust.", ja: "日次チェックが効きます。1日だけ支出を記録して調整しましょう。" },
      { en: "Avoid pessimism. Small, steady saving is effective.", ja: "悲観しすぎないで。小さな節約の継続が効きます。" },
      { en: "If you feel uncertain, delay. A postponed purchase is often the best purchase.", ja: "迷うなら延期を。買わないことが最良の買い物になることもあります。" },
      { en: "Keep a buffer. Even a small emergency fund reduces anxiety.", ja: "余裕を持ちましょう。小さな予備費でも不安が減ります。" },
      { en: "Check your receipts and subscriptions. One oversight is likely.", ja: "レシートやサブスクを確認。見落としが1つありそうです。" },
      { en: "Stay consistent. Avoid big swings in spending.", ja: "一貫性を保って。支出の大きな波は避けましょう。" },
    ],
    c: [
      { en: "Be cautious with money today. Avoid risky deals and keep everything documented.", ja: "今日は金銭面を慎重に。リスクのある話は避け、必ず記録を残しましょう。" },
      { en: "A hidden cost is possible. Read the fine print and confirm the total.", ja: "隠れコストがありそうです。細則を読み、総額を確認してください。" },
      { en: "Do not lend or borrow casually. Clear boundaries protect relationships.", ja: "気軽な貸し借りはしないで。境界線が関係を守ります。" },
      { en: "If you shop when tired, you may regret it. Postpone until you feel calm.", ja: "疲れて買うと後悔しがちです。落ち着いてからにしましょう。" },
      { en: "Avoid subscription traps. Cancel what you do not actively use.", ja: "サブスク沼に注意。積極的に使っていないものは解約を。" },
      { en: "Keep your budget strict today. Treat it like a contract with yourself.", ja: "今日は予算を厳守。自分との契約だと思って守りましょう。" },
      { en: "If someone pressures you, say no. A rushed decision can create loss.", ja: "急かされても断ってください。焦った判断は損につながります。" },
      { en: "Avoid expensive experiments. Choose reliable options you already trust.", ja: "高価な実験は避けて。既に信頼できる選択肢を。" },
      { en: "Recheck payments. A small mistake can happen easily today.", ja: "支払いを再確認。今日は小さなミスが起きやすいです。" },
      { en: "Keep purchases minimal. Maintenance is enough for now.", ja: "買い物は最小限に。今は維持で十分です。" },
      { en: "Do not mix emotion and money. Decide with numbers and facts.", ja: "感情とお金を混ぜないで。数字と事実で判断しましょう。" },
      { en: "If you must sign, read twice. Accuracy prevents regret.", ja: "署名が必要なら2回読む。正確さが後悔を防ぎます。" },
    ],
  },

  health: {
    a: [
      { en: "Your recovery is strong today. A short walk or light exercise will boost energy.", ja: "今日は回復力が高いです。短い散歩や軽い運動でエネルギーが上がります。" },
      { en: "Your body responds well to routine. Sleep a bit earlier and you will feel refreshed.", ja: "身体がルーティンに反応しやすい日です。少し早く寝るとスッキリします。" },
      { en: "Hydration helps more than usual. Drink water and your focus will improve.", ja: "今日は水分が特に効きます。水を飲むと集中も上がります。" },
      { en: "Posture and breathing matter. Fix them for two minutes and you will reset quickly.", ja: "姿勢と呼吸が重要です。2分整えるだけで素早くリセットできます。" },
      { en: "A clean meal supports you. Choose simple food and your mood becomes stable.", ja: "シンプルな食事が支えになります。簡単なものを選ぶと気分も安定します。" },
      { en: "Today supports training habits. Keep it light but consistent.", ja: "今日は運動習慣に追い風。軽くても継続を。" },
      { en: "You can improve efficiency by resting properly. One good break will raise your output.", ja: "休み方が効率を上げます。良い休憩が成果を押し上げます。" },
      { en: "Stress drops if you simplify. Reduce one obligation and feel the difference.", ja: "シンプルにするとストレスが下がります。義務を一つ減らして違いを感じてください。" },
      { en: "Your energy is balanced. Maintain a steady pace and avoid extremes.", ja: "エネルギーが整っています。極端を避け、一定のペースで。" },
      { en: "A small improvement is easy today. Adjust one habit and keep it.", ja: "小さな改善がしやすい日です。習慣を一つ調整して継続を。" },
      { en: "If you move your body early, the day becomes smoother.", ja: "早い時間に体を動かすと、一日がスムーズになります。" },
      { en: "Your mindset is calm. That alone supports your health.", ja: "心が落ち着いています。それ自体が健康を支えます。" },
    ],
    b: [
      { en: "Keep your routine stable. Small changes are fine, but avoid overdoing it.", ja: "ルーティンを安定させましょう。小さな変更はOKですが、やりすぎは避けて。" },
      { en: "If you feel tired, take a short break. Consistency matters more than intensity.", ja: "疲れたら短い休憩を。強度より継続が大事です。" },
      { en: "Sleep quality is the key. Reduce screen time before bed.", ja: "鍵は睡眠の質です。就寝前の画面時間を減らしましょう。" },
      { en: "A light stretch will help. Two minutes is enough.", ja: "軽いストレッチが効きます。2分で十分です。" },
      { en: "Avoid skipping meals. A simple meal keeps energy stable.", ja: "食事抜きは避けて。簡単な食事でエネルギーが安定します。" },
      { en: "Hydration and posture: check both once.", ja: "水分と姿勢、両方を一度チェック。" },
      { en: "Do not chase perfection. A reasonable routine is sustainable.", ja: "完璧を追わないで。無理のない習慣が続きます。" },
      { en: "If you feel tense, breathe slowly. A calm rhythm reduces stress.", ja: "緊張したらゆっくり呼吸。落ち着いたリズムがストレスを下げます。" },
      { en: "Today is good for maintenance. Clean up your environment and your mind will relax.", ja: "今日は整備向きです。環境を整えると心も緩みます。" },
      { en: "Keep a steady pace. Extreme effort will not pay off today.", ja: "一定のペースで。極端な頑張りは報われにくい日です。" },
      { en: "If you need motivation, start small. One minute counts.", ja: "やる気が要るなら小さく始めましょう。1分でも価値があります。" },
      { en: "Notice your body signals. Adjust before it becomes a problem.", ja: "身体のサインに気づいて。問題になる前に調整しましょう。" },
    ],
    c: [
      { en: "Your body may be sensitive today. Lower intensity and prioritize recovery.", ja: "今日は体が敏感になりやすいです。強度を下げ、回復を優先しましょう。" },
      { en: "Do not ignore fatigue. Sleep and hydration are more important than productivity.", ja: "疲れを無視しないで。生産性より睡眠と水分が重要です。" },
      { en: "Avoid caffeine overload. Keep stimulants moderate.", ja: "カフェインの摂りすぎに注意。刺激は控えめに。" },
      { en: "If stress increases, reduce obligations. Protect your schedule.", ja: "ストレスが増えるなら義務を減らして。予定を守りましょう。" },
      { en: "A small discomfort can grow. Address it early and keep things simple.", ja: "小さな不調が大きくなりやすいです。早めに対処し、シンプルに過ごして。" },
      { en: "Avoid intense training. A gentle walk is enough.", ja: "強い運動は避けて。やさしい散歩で十分です。" },
      { en: "Your focus may drop. Take breaks and avoid long sessions.", ja: "集中が落ちやすいです。休憩を挟み、長時間の作業は避けましょう。" },
      { en: "If you feel irritated, rest your eyes and breathe. Reset before you respond.", ja: "イライラしたら目を休めて呼吸を。反応する前にリセットを。" },
      { en: "Today is for maintenance. Clean,整理, and prepare for tomorrow.", ja: "今日は整備日。掃除・整理をして明日に備えましょう。" },
      { en: "Avoid extremes in food and sleep. Stability is the best medicine today.", ja: "食事も睡眠も極端は避けて。今日は安定が最良の薬です。" },
      { en: "Keep your body warm and protect recovery.", ja: "体を冷やさず、回復を守りましょう。" },
      { en: "If you feel heavy, simplify your day. Minimum effort, maximum care.", ja: "重さを感じたら一日をシンプルに。最小の負荷で、最大のケアを。" },
    ],
  },
};
